name: Publish on GitHub, CurseForge & Modrinth

on: [ workflow_dispatch ]

env:
  MOD_NAME: "Hexed"
  VERSION: "0.8.3"
  MINECRAFT_VERSION: "1.20.1"
  JAVA_VERSION: 17
  VERSION_TYPE: beta

  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

permissions:
  contents: write

jobs:
  set_release_name:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_NAME: ${{ steps.set_release_name.outputs.RELEASE_NAME }}
    steps:
      - name: Set Release Name
        id: set_release_name
        run: echo "::set-output name=RELEASE_NAME::${{ env.MOD_NAME }} ${{ env.VERSION }}+MC${{ env.MINECRAFT_VERSION }}"

  build:
    needs: set_release_name
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 996912
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          github-tag: "v${{env.VERSION}}+${{ env.MINECRAFT_VERSION }}"
          github-token: "${{env.GITHUB_TOKEN}}"

          modrinth-id: wUMNoII3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true

          name: "${{ needs.set_release_name.outputs.RELEASE_NAME }}"
          version: "${{env.VERSION}}"
          version-type: "${{env.VERSION_TYPE}}"
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"